In [5]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_digits
digits = load_digits()

In [4]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [7]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.2)

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [15]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [16]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [22]:
def get_score(model, x_train, x_test, y_train, y_test):
    model.fit(x_train, y_train)
    return model.score(x_test, y_test)

In [23]:
get_score(LogisticRegression(max_iter=5000), x_train, x_test, y_train, y_test)

0.975

In [26]:
get_score(SVC(), x_train, x_test, y_train, y_test)

0.9916666666666667

In [27]:
get_score(RandomForestClassifier(), x_train, x_test, y_train, y_test)

0.975

**Another Approach**

In [28]:
#better folding
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [39]:
scores_lg = []
scores_svm = []
scores_rf = []

In [40]:
for train_index, test_index in kf.split(digits.data):
    x_train, x_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    
    scores_lg.append(get_score(LogisticRegression(max_iter=5000), x_train, x_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), x_train, x_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(), x_train, x_test, y_train, y_test))

In [41]:
scores_lg

[0.9282136894824707, 0.9415692821368948, 0.9165275459098498]

In [42]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [43]:
scores_rf

[0.9382303839732888, 0.9499165275459098, 0.9265442404006677]